version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always

  chat:
    image: n03l97/pvs-chat
    restart: always
    ports:
      - 9700:3000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
